# Generated by Django 4.0.6 on 2022-07-14 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_post'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='aPost',
        ),
    ]
