# Generated by Django 4.0.6 on 2022-07-14 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_rename_post_apost'),
    ]

    operations = [
        migrations.AddField(
            model_name='apost',
            name='message',
            field=models.TextField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
