# Generated by Django 4.0.6 on 2022-07-14 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_apost_message'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='aPost',
            new_name='Post',
        ),
    ]
